# Generated by Django 3.1.2 on 2020-11-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bece', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
